spring.application.name=tfl-api

# Swagger / OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/tfl
spring.datasource.username=postgres
spring.datasource.password=password

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#JWT Config
jwt.secret = klsdjflksdjflksdjflksdjflksdjlkf3434f3frd355t53g6g4g6g4g
#expires in 24 hours
jwt.expiration = 86400000

